services:
  - type: web
    name: readwise-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
